# Generated by Django 6.0.6 on 2026-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opening_hours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_limit_new', models.PositiveIntegerField(default=30)),
                ('order_limit_confirmed', models.PositiveIntegerField(default=45)),
                ('order_limit_preparing', models.PositiveIntegerField(default=60)),
                ('order_limit_ready', models.PositiveIntegerField(default=90)),
                ('booking_warn_new_minutes', models.PositiveIntegerField(default=60)),
                ('booking_problem_new_minutes', models.PositiveIntegerField(default=180)),
                ('booking_warn_confirmed_hours', models.PositiveIntegerField(default=24)),
            ],
            options={
                'verbose_name': 'Dashboard SLA beállítások',
                'verbose_name_plural': 'Dashboard SLA beállítások',
            },
        ),
    ]
