# Generated by Django 6.0.6 on 2026-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_created_at_remove_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('confirmed', 'Elfogadva'), ('preparing', 'Készül'), ('ready', 'Kiszállítás alatt'), ('delivered', 'Kézbesítve'), ('cancelled', 'Sikertelen kézbesítés')], default='new', max_length=20),
        ),
    ]
