# Generated by Django 6.0.6 on 2026-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('Foglalás', 'Foglalás'), ('Visszajelzés', 'Visszajelzés'), ('Általános kérdés', 'Általános kérdés'), ('Egyéb', 'Egyéb')], default='Egyéb', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Új'), ('read', 'Olvasott'), ('answered', 'Megválaszolva')], default='new', max_length=20),
        ),
    ]
