# Generated by Django 6.0.6 on 2026-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, choices=[('csaladi', 'Családi összejövetel'), ('uzleti', 'Üzleti ebéd / vacsora'), ('szulinap', 'Születésnap'), ('evfordulo', 'Évforduló'), ('egyeb', 'Egyéb')], max_length=20, null=True),
        ),
    ]
