# Generated by Django 6.0.6 on 2026-06-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('soup', 'Soup'), ('main', 'Main Course'), ('dessert', 'Dessert')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='allergen',
            name='code',
        ),
        migrations.AddField(
            model_name='allergen',
            name='key',
            field=models.CharField(default='temp', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergen',
            name='label',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allergen',
            name='icon',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='weeklymenu',
            unique_together={('day', 'menu_type')},
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='dessert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_desserts', to='menu.weeklymenuitem'),
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='main_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_mains', to='menu.weeklymenuitem'),
        ),
        migrations.AlterField(
            model_name='weeklymenu',
            name='soup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_soups', to='menu.weeklymenuitem'),
        ),
    ]
